name = "portfolio"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]
