name = "quoridor-ws"
main = "worker.js"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "QUORIDOR_ROOM"
class_name = "QuoridorRoom"

[[migrations]]
tag = "v1"
new_classes = ["QuoridorRoom"]
